name: PHP Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install SVN
        run: sudo apt-get install subversion

      - name: Start MySQL
        run: sudo /etc/init.d/mysql start

      - name: Install WP Tests
        run: ./bin/install-wp-tests.sh wptests root root
  
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
  
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPUnit Tests
        run: composer run test

      - name: Run PHPCS
        run: composer run phpcs:full
